name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run install
        run: npm install
      - name: Build site
        run: npm run build
      - name: Build library
        run: npm run package
