name: Nightly MCU release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly-mcu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          repository: material-foundation/material-color-utilities
          path: upstream

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: upstream/typescript
        run: npm install

      - name: Fix TypeScript config for nightly
        working-directory: upstream/typescript
        run: |
          node -p "
            const config = require('./tsconfig.json');
            config.compilerOptions.noUnusedLocals = false;
            config.compilerOptions.noUnusedParameters = false;
            JSON.stringify(config, null, 2);
          " > tsconfig.tmp.json
          mv tsconfig.tmp.json tsconfig.json

      - name: Build package
        working-directory: upstream/typescript
        run: npm run build

      - name: Fix import extensions for Node.js compatibility
        working-directory: upstream/typescript
        run: |
          echo "=== Files before fixing ==="
          find . -name "*.js" -not -path "./node_modules/*" | head -10

          echo "=== Sample imports before fixing ==="
          find . -name "*.js" -not -path "./node_modules/*" -exec grep -l "from '\\.\\." {} + | head -3 | xargs grep "from '\\.\\."

          echo "=== Applying fix ==="
          find . -name "*.js" -not -path "./node_modules/*" -exec sed -i -E \
            -e "s|from '(\.\.?/[^']*)'|from '\1.js'|g" \
            -e "s|\.js\.js'|.js'|g" \
            {} +

          echo "=== Sample imports after fixing ==="
          find . -name "*.js" -not -path "./node_modules/*" -exec grep -l "from '\\.\\." {} + | head -3 | xargs grep "from '\\.\\."

          echo "=== Files that will be published ==="
          ls -la

          echo "=== Contents of package.json (to verify what gets published) ==="
          cat package.json | jq '.files // "no files field - publishes everything except node_modules"'

      - name: Update package.json for nightly
        working-directory: upstream/typescript
        run: |
          NIGHTLY_VERSION=$(node -p "
            const pkg = require('./package.json');
            const date = Date.now();
            \`\${pkg.version}\${date}\`;
          ")

          node -p "
            const pkg = require('./package.json');
            pkg.name = '@ktibow/material-color-utilities-nightly';
            pkg.version = process.env.NIGHTLY_VERSION;
            JSON.stringify(pkg, null, 2);
          " > package.tmp.json
          mv package.tmp.json package.json
        env:
          NIGHTLY_VERSION: ${{ env.NIGHTLY_VERSION }}

      - name: Publish to npm
        working-directory: upstream/typescript
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
